project:
  type: website
  output-dir: docs

website:
  title: "Mapd'O"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: methode.qmd
        text: Méthode de segmentation
      - href: méthodo.qmd
        text: Méthologie

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual