---
title: "Méthodologie"
---

Vous pouvez comparer les méthodes de segmentation selon plusieurs sources de données:

## Données d'exemple

L'application a été crée dans un objectif de segmenter des données longitudinales sur des variables géomorphologiques de rivière. Les données d'exemples proviennent de la [Fluvial Corridor Toolbox](https://tramebleue.github.io/fct-cli/) (Dunesmes et al., 2024). On retrouve un grand nombre de descripteurs comme la largeur de la bande active ou la largeur de fond de vallée. Les données sont spatialisées et sont observables dans la carte juste en dessous du graphique. La localisation des rupture est symbolisée par des points rouge dans la carte.

## Données simulées

Vous pouvez créer votre propre série afin de contrôler l'ensemble des paramètre comme le nombre de rupture (K) afin de la faire correspondre plus ou moins avec vos données. Vous pourrez ensuite comparer l'ensemble des méthodes de segmentation sur votre série. Pour en savoir plus dans la génération de la série, voir De Almeida et al., in press.

Plusieurs paramètre sont possibles:

-   N : Longueur totale de la série

-   K : Nombre de rupture dans la série

-   Ratio R : Ratio qui détermine l'équilibre entre l'écart-type inter-segment et intra-segment. Il influence la capacité à segmenter correctement en ajustant les niveaux de bruit et les valeurs moyennes de chaque segment. Pour résumer, cela correspond à la difficulté d'une série à être segmentée.

-   Delta : Coefficient qui détermine le type de transition entre les segments et est basé sur la longueur de la série. Si delta = 0, alors les segments sont collés tandis que si Delta est positif, alors une transition graduelle est placée entre les segments.

## Importation de données

Enfin, il est possible d'importer vos propres données depuis un .CSV
